/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;

/**
 * jFrame form to create a Admin Frame
 *
 * @author maria
 */
public class AdminFrame extends javax.swing.JFrame {

    //Data members
    private Admin admin;
    protected static List<Course> courses = (List<Course>) 
            User.deserializeObj("Course.ser");

    /**
     * Creates new form AdminFrame
     *
     * @param admin
     */
    public AdminFrame(Admin admin) {
        initComponents();
        greetingsL.setText(greetingsL.getText() + admin.getName());
        this.admin = admin;

        ImageIcon adminImage = new ImageIcon("src\\project2\\admin.png");
        iconL.setIcon(adminImage);
        teacherL.setVisible(false);
        teacherTF.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        greetingsL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        studentRB = new javax.swing.JRadioButton();
        teacherRB = new javax.swing.JRadioButton();
        courseRB = new javax.swing.JRadioButton();
        nameL = new javax.swing.JLabel();
        teacherL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        teacherTF = new javax.swing.JTextField();
        addB = new javax.swing.JButton();
        messageL = new javax.swing.JLabel();
        displayB = new javax.swing.JButton();
        displayWindowL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayWindowTA = new javax.swing.JTextArea();
        iconL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");

        greetingsL.setText("Welcome, ");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Add new elements");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(studentRB);
        studentRB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        studentRB.setSelected(true);
        studentRB.setText("Student");
        studentRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(teacherRB);
        teacherRB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        teacherRB.setText("Teacher");
        teacherRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(courseRB);
        courseRB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        courseRB.setText("Course");
        courseRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseRBActionPerformed(evt);
            }
        });

        nameL.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        nameL.setText("Name:");

        teacherL.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        teacherL.setText("Teacher:");

        nameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTFKeyPressed(evt);
            }
        });

        teacherTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teacherTFKeyPressed(evt);
            }
        });

        addB.setText("Add");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        messageL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseRB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageL, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(addB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentRB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teacherRB, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameL)
                            .addComponent(teacherL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teacherTF, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(nameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(studentRB)
                        .addComponent(nameL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherRB)
                    .addComponent(teacherL)
                    .addComponent(teacherTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(courseRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(messageL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addB)
                        .addContainerGap())))
        );

        displayB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        displayB.setText("Display");
        displayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBActionPerformed(evt);
            }
        });

        displayWindowL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        displayWindowL.setText("Display Window");

        displayWindowTA.setColumns(20);
        displayWindowTA.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        displayWindowTA.setForeground(new java.awt.Color(0, 0, 0));
        displayWindowTA.setRows(5);
        displayWindowTA.setCaretColor(new java.awt.Color(0, 0, 0));
        displayWindowTA.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        displayWindowTA.setEnabled(false);
        displayWindowTA.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(displayWindowTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(greetingsL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(iconL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayWindowL)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayB)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(greetingsL)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(displayWindowL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(iconL))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayB)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method to erase and hide labels and text field when this button is pressed
     * @param evt the event
     */
    private void courseRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseRBActionPerformed
        nameTF.setText("");
        teacherL.setVisible(true);
        teacherTF.setVisible(true);
        displayWindowTA.setText("");
    }//GEN-LAST:event_courseRBActionPerformed

    /**
     * Method to erase and hide labels and text field when this button is pressed
     * @param evt the event
     */
    private void studentRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRBActionPerformed
        nameTF.setText("");
        teacherL.setVisible(false);
        teacherTF.setVisible(false);
        displayWindowTA.setText("");
    }//GEN-LAST:event_studentRBActionPerformed

    /**
     * Method to add a student, teacher and course
     * @param evt the event
     */
    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed

        if (courses == null) {
            courses = new ArrayList<>();
        }

        try {
            if (studentRB.isSelected()) {
                LoginFrame.students.add(new Student(nameTF.getText(), "1234"));
                User.serializeObj("Student.ser", LoginFrame.students);
                messageL.setForeground(Color.GREEN);
                messageL.setText("Student added successfully");
                
            } else if (teacherRB.isSelected()) {
                LoginFrame.teachers.add(new Teacher(nameTF.getText(), "1234"));
                User.serializeObj("Teacher.ser", LoginFrame.teachers);
                messageL.setForeground(Color.GREEN);
                messageL.setText("Teacher added successfully");
                
            } else if (courseRB.isSelected()) {
                for (Teacher teacher : LoginFrame.teachers) {
                    if (teacherTF.getText().equals(teacher.name)) {
                        courses.add(new Course(nameTF.getText(), teacher));
                        User.serializeObj("Course.ser", courses);
                        messageL.setForeground(Color.GREEN);
                        messageL.setText("Course added");
                    } else {
                        messageL.setText("");
                        messageL.setForeground(Color.RED);
                        messageL.setText("Error: Teacher not Found");
                    }
                }
            }
            nameTF.setText("");
            teacherTF.setText("");
        } catch (Exception e) {
            System.out.printf("Error: %s", e);
        }
    }//GEN-LAST:event_addBActionPerformed

    /**
     * Method to display the information of the selected button option
     * @param evt the event
     */
    private void displayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBActionPerformed
        String str = "";

        try {
            if (studentRB.isSelected()) {
                str += String.format("%s", "Students\n");
                for (Student student : LoginFrame.students) {
                    str += String.format("\n%s: %s\n", "ID ", student.id);
                    str += String.format("%s: %s\n", "Name ", student.name);
                    for (Course regCourse : student.getRegsCourses()) {
                        str += String.format("%s: %s\n", "Registered Courses ",
                                regCourse.getName());
                    }
                }
            } else if (teacherRB.isSelected()) {
                str += String.format("%s", "Teachers\n");
                for (Teacher teacher : LoginFrame.teachers) {
                    str += String.format("\n%s: %s\n", "ID ", teacher.id);
                    str += String.format("%s: %s\n", "Name ", teacher.name);
                    str += String.format("%s: %s\n", "Teaching Courses ",
                            teacher.getTeachingCourses());
                }
            } else if (courseRB.isSelected()) {
                str += String.format("%s", "Courses\n");
                for (Course course : courses) {
                    str += String.format("\n%s: %s\n", "Course ", course.getName());
                    str += String.format("%s: %s\n", "Teacher ",
                            course.getTeacher().name);
                    str += String.format("%s: %s\n", "Max Student ",
                            course.getMaxStuAmount());
                }
            }
            displayWindowTA.setText(str);
        } catch (Exception e) {
            System.out.printf("Error: %s", e);
        }
    }//GEN-LAST:event_displayBActionPerformed

    /**
     * Method to erase and hide labels and text field when this button is pressed
     * @param evt the event
     */
    private void teacherRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherRBActionPerformed
        nameTF.setText("");
        teacherL.setVisible(false);
        teacherTF.setVisible(false);
        displayWindowTA.setText("");
    }//GEN-LAST:event_teacherRBActionPerformed

    /**
     * Method to perform the add button when pressed enter
     * @param evt the event
     */
    private void teacherTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teacherTFKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            addB.doClick();
        }
    }//GEN-LAST:event_teacherTFKeyPressed

    /**
     * Method to perform the add button when pressed enter
     * @param evt the event
     */
    private void nameTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTFKeyPressed
        if (!"".equals(nameTF.getText())) {
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
                addB.doClick();
            }
        }
    }//GEN-LAST:event_nameTFKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton courseRB;
    private javax.swing.JButton displayB;
    private javax.swing.JLabel displayWindowL;
    private javax.swing.JTextArea displayWindowTA;
    private javax.swing.JLabel greetingsL;
    private javax.swing.JLabel iconL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageL;
    private javax.swing.JLabel nameL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JRadioButton studentRB;
    private javax.swing.JLabel teacherL;
    private javax.swing.JRadioButton teacherRB;
    private javax.swing.JTextField teacherTF;
    // End of variables declaration//GEN-END:variables
}
