/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.ImageIcon;

/**
 * jFrame form to create a Login Frame
 *
 * @author maria
 */
public class LoginFrame extends javax.swing.JFrame {

    //Data members
    protected static List<Student> students = (List<Student>) 
            User.deserializeObj("Student.ser");
    protected static List<Teacher> teachers = (List<Teacher>) 
            User.deserializeObj("Teacher.ser");
    protected static List<Admin> admins = (List<Admin>) 
            User.deserializeObj("Admin.ser");

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();

        ImageIcon scoreImage = new ImageIcon("src\\project2\\score.png");
        iconL.setIcon(scoreImage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        idL = new javax.swing.JLabel();
        passwordL = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        messageL = new javax.swing.JLabel();
        submitB = new javax.swing.JButton();
        passwordPF = new javax.swing.JPasswordField();
        iconL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        titleL.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titleL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleL.setText("Vanier Score System");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        idL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        idL.setText("ID:");

        passwordL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        passwordL.setText("Password:");

        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });
        idTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTFKeyPressed(evt);
            }
        });

        messageL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        messageL.setForeground(new java.awt.Color(255, 0, 0));
        messageL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        submitB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        submitB.setText("Submit");
        submitB.setSelected(true);
        submitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBActionPerformed(evt);
            }
        });

        passwordPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordPFKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordL))
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idTF)
                    .addComponent(passwordPF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(messageL, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(submitB, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idL)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordL)
                    .addComponent(passwordPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(messageL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(submitB)
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iconL)
                        .addGap(47, 47, 47)
                        .addComponent(titleL)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleL)
                    .addComponent(iconL))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    /**
     * Method to submit an admin or student or teacher
     *
     * @param evt the event
     */
    private void submitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBActionPerformed

        boolean findId = false;

        if (students == null) {
            students = new ArrayList<>();
        } else if (teachers == null) {
            teachers = new ArrayList<>();
        }

        try {
            for (Student student : students) {
                if (student.id.equals(idTF.getText().toUpperCase())) {
                    findId = true;
                }
                if (findId) {
                    if (Arrays.equals(passwordPF.getPassword(),
                            student.password.toCharArray())) {
                        messageL.setText("");
                        this.setVisible(false);
                        new StudentFrame(student).setVisible(true);
                        return;
                    }
                }
            }

            for (Teacher teacher : teachers) {
                if (teacher.id.equals(idTF.getText().toUpperCase())) {
                    findId = true;
                }
                if (findId) {
                    if (Arrays.equals(passwordPF.getPassword(),
                            teacher.password.toCharArray())) {
                        messageL.setText("");
                        this.setVisible(false);
                        new TeacherFrame(teacher).setVisible(true);
                        return;
                    }
                }
            }

            for (Admin admin : admins) {
                if (admin.id.equals(idTF.getText().toUpperCase())) {
                    findId = true;
                }
                if (findId) {
                    if (Arrays.equals(passwordPF.getPassword(),
                            admin.password.toCharArray())) {
                        messageL.setText("");
                        this.setVisible(false);
                        new AdminFrame(admin).setVisible(true);
                        return;
                    }
                }
            }
        } catch (Exception e) {
            System.out.printf("Error: %s", e);
        }
        messageL.setText("Your input is invalid");
        idTF.setText("");
        passwordPF.setText("");
    }//GEN-LAST:event_submitBActionPerformed

    /**
     * Method to activate the submit button when pressed enter after the
     * password is entered
     *
     * @param evt the event
     */
    private void passwordPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordPFKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            submitB.doClick();
        }
    }//GEN-LAST:event_passwordPFKeyPressed

    /**
     * Method to activate the password field when pressed enter
     *
     * @param evt
     */
    private void idTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTFKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            passwordPF.requestFocus();
        }
    }//GEN-LAST:event_idTFKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        // Code below for testing purposes and creating a new admin        
//        List<Admin> admins = new ArrayList<>();
//        Admin a1 = new Admin("Princess", "1234");
//        admins.add(a1);
//        User.serializeObj("Admin.ser", admins);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconL;
    private javax.swing.JLabel idL;
    private javax.swing.JTextField idTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel messageL;
    private javax.swing.JLabel passwordL;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JButton submitB;
    private javax.swing.JLabel titleL;
    // End of variables declaration//GEN-END:variables
}
