/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.awt.Color;

/**
 * jFrame form to create a Student Frame
 *
 * @author maria
 */
public class StudentFrame extends javax.swing.JFrame {

    //Data members
    private Student student;
    private int positionRemaning = 1;

    /**
     * Creates new form StudentFrame
     *
     * @param student a student from the student class
     */
    public StudentFrame(Student student) {
        initComponents();
        this.student = student;
        greetingsL.setText(greetingsL.getText() + student.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greetingsL = new javax.swing.JLabel();
        registerACourseL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        courseL = new javax.swing.JLabel();
        courseTF = new javax.swing.JTextField();
        checkCourseInfoB = new javax.swing.JButton();
        registerB = new javax.swing.JButton();
        messageL = new javax.swing.JLabel();
        displayL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        displayScoreB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student");

        greetingsL.setText("Welcome, ");

        registerACourseL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        registerACourseL.setText("Register a course");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        courseL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        courseL.setText("Course:");

        checkCourseInfoB.setText("Check Course Info");
        checkCourseInfoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCourseInfoBActionPerformed(evt);
            }
        });

        registerB.setText("Register");
        registerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBActionPerformed(evt);
            }
        });

        messageL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(courseL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(courseTF)
                    .addComponent(checkCourseInfoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerB))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(messageL, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseL)
                    .addComponent(courseTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(checkCourseInfoB)
                .addGap(18, 18, 18)
                .addComponent(registerB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(messageL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        displayL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        displayL.setText("Display");

        displayTA.setEditable(false);
        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        displayScoreB.setText("Display  Score");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(greetingsL)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerACourseL)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayL)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayScoreB)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(greetingsL)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerACourseL)
                    .addComponent(displayL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addComponent(displayScoreB))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method to check the information of a course
     *
     * @param evt the event
     */
    private void checkCourseInfoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCourseInfoBActionPerformed
        String str = "";

        for (Course course : AdminFrame.courses) {
            if (course.getName().equals(courseTF.getText())) {
                str += String.format("%s", "Courses Info\n");
                str += String.format("\n%s: %s\n", "Course ", course.getName());
                str += String.format("%s: %s\n", "Teacher ",
                        course.getTeacher().name);
                str += String.format("%s: %d\n", "Max Student ",
                        course.getMaxStuAmount());
                str += String.format("%s: %s\n", "Remaining Position ",
                        course.getMaxStuAmount() - positionRemaning);
                messageL.setText("");
            } else {
                messageL.setForeground(Color.RED);
                messageL.setText("Course does not exist!");
            }
        }
        displayTA.setText(str);
    }//GEN-LAST:event_checkCourseInfoBActionPerformed
    /**
     * Method to register a student to a course
     *
     * @param evt the event
     */
    private void registerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBActionPerformed
        try {
            for (Course course : AdminFrame.courses) {
                if (course.getName().equals(courseTF.getText())) {
                    student.getRegsCourses().add(course);
                    course.getRegsStudents().add(student);
                    User.serializeObj("Student.ser", LoginFrame.students);
                    User.serializeObj("Course.ser", AdminFrame.courses);
                }
            }
        } catch (Exception e) {
            System.out.printf("Error: %s", e);
        }
    }//GEN-LAST:event_registerBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkCourseInfoB;
    private javax.swing.JLabel courseL;
    private javax.swing.JTextField courseTF;
    private javax.swing.JLabel displayL;
    private javax.swing.JButton displayScoreB;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JLabel greetingsL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageL;
    private javax.swing.JLabel registerACourseL;
    private javax.swing.JButton registerB;
    // End of variables declaration//GEN-END:variables
}
