/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * jFrame form to create a Teacher Frame
 *
 * @author maria
 */
public class TeacherFrame extends javax.swing.JFrame {

    //Data members
    private Teacher teacher;

    /**
     * Creates new form TeacherFrame
     *
     * @param teacher the teacher
     */
    public TeacherFrame(Teacher teacher) {
        initComponents();
        greetingsL.setText(greetingsL.getText() + teacher.getName());
        this.teacher = teacher;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        greetingsL = new javax.swing.JLabel();
        addAScoreL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        courseL = new javax.swing.JLabel();
        studentL = new javax.swing.JLabel();
        scoreL = new javax.swing.JLabel();
        courseTF = new javax.swing.JTextField();
        studentTF = new javax.swing.JTextField();
        scoresTF = new javax.swing.JTextField();
        addB = new javax.swing.JButton();
        messageL = new javax.swing.JLabel();
        displayL = new javax.swing.JLabel();
        displayTA = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        displayB = new javax.swing.JButton();
        exportB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teacher");

        greetingsL.setText("Welcome, ");

        addAScoreL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addAScoreL.setText("Add a score");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(60, 63, 65));

        courseL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        courseL.setText("Course:");

        studentL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        studentL.setText("Student:");

        scoreL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        scoreL.setText("Scores:");

        scoresTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoresTFActionPerformed(evt);
            }
        });

        addB.setText("Add");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        messageL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studentL)
                                    .addComponent(scoreL)
                                    .addComponent(courseL))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(courseTF, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(studentTF)
                                        .addComponent(scoresTF, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(messageL, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseL)
                    .addComponent(courseTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentL)
                    .addComponent(studentTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreL)
                    .addComponent(scoresTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(addB)
                .addGap(18, 18, 18)
                .addComponent(messageL, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        displayL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        displayL.setText("Display");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        displayTA.setViewportView(jTextArea1);

        displayB.setText("Display");
        displayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBActionPerformed(evt);
            }
        });

        exportB.setText("Export");
        exportB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addAScoreL)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayL)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(displayB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exportB, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(displayTA, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(greetingsL)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(greetingsL)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAScoreL)
                    .addComponent(displayL))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displayTA, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayB)
                            .addComponent(exportB)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoresTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoresTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoresTFActionPerformed

    /**
     * Method to add the score to a specific student of a specific course
     * Method incomplete...
     *
     * @param evt
     */
    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed

//        for (Course course : AdminFrame.courses) {
//            for (Student student : LoginFrame.students) {
//                if (course.getRegsStudents().equals(studentTF.getText())
//                        && student.getRegsCourses().equals(courseTF.getText())) {
//                    
//                }
//            }
//        }
    }//GEN-LAST:event_addBActionPerformed

    /**
     * Method to display the course name, student name and score
     * @param evt the event
     */
    private void displayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayBActionPerformed

    /**
     * Method to export the course name, student name and score to a CSV file
     * @param evt the event
     */
    private void exportBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBActionPerformed
//        try (FileWriter fw = new FileWriter(new File
//        ("src\\project2\\courseName.csv"))) {
//            PrintWriter pw = new PrintWriter(fw);
//            for (Course course : AdminFrame.courses) {
//                for (Student student : LoginFrame.students) {
//                    pw.printf("%s,", course.getName());
//                    pw.printf("%s,", student.name);
//                    pw.printf("%s,", course.getFinalScores());
//                }
//                pw.println();
//            }
//        } catch (IOException ex) {
//            System.out.println("Invalid");
//        }
    }//GEN-LAST:event_exportBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addAScoreL;
    private javax.swing.JButton addB;
    private javax.swing.JLabel courseL;
    private javax.swing.JTextField courseTF;
    private javax.swing.JButton displayB;
    private javax.swing.JLabel displayL;
    private javax.swing.JScrollPane displayTA;
    private javax.swing.JButton exportB;
    private javax.swing.JLabel greetingsL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel messageL;
    private javax.swing.JLabel scoreL;
    private javax.swing.JTextField scoresTF;
    private javax.swing.JLabel studentL;
    private javax.swing.JTextField studentTF;
    // End of variables declaration//GEN-END:variables
}
